FROM rust:1.77-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch

COPY Cargo.toml Cargo.lock ./
COPY src ./src

EXPOSE 3000

CMD ["cargo", "watch", "-x", "run"]
